version: '3.9'

networks:
  dev:
    driver: bridge

services:
  art-gallery-api:
    image: docker.io/library/art-gallery-api
    depends_on:
      - "dev_db"
    container_name: art-gallery-api-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=dev_db;User Id=postgres;Password=PostgreSQL;Port:5433;Database=art_gallery_db;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  dev_db:
    image: postgres:latest
    container_name: dev_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PostgreSQL
      - POSTGRES_DB=art_gallery_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  db_data:
